# Generated by Django 4.2.6 on 2023-10-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
