# Generated by Django 4.2.6 on 2023-11-02 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_user_id_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAgent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('state', models.CharField(choices=[('pending', 'PENDING'), ('accept', 'ACCEPT'), ('reject', 'REJECT')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.user')),
            ],
        ),
    ]
