# Generated by Django 4.2.6 on 2023-11-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_requestagent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestagent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
