# Generated by Django 4.2.6 on 2023-11-02 23:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_requestagent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestagent',
            name='id',
        ),
        migrations.AddField(
            model_name='requestagent',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
