# Generated by Django 4.2.6 on 2023-11-24 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_user_user_id_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agent_agent_id', to='client.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_user_id', to='client.user'),
        ),
    ]
