# Generated by Django 4.2.6 on 2023-12-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='uploads/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.user')),
            ],
        ),
    ]
