# Generated by Django 4.2.6 on 2023-12-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_userpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
