# Generated by Django 4.2.6 on 2023-12-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_user_otp_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferencesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_suspend_account', models.BooleanField(default=False)),
                ('device_configuration_change', models.BooleanField(default=False)),
                ('request_agent_response', models.BooleanField(default=False)),
                ('reached_max_visitors', models.BooleanField(default=True)),
                ('hight_max_visitors', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.user')),
            ],
        ),
    ]
