# Generated by Django 4.2.6 on 2023-12-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_notificationpreferencesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationpreferencesmodel',
            old_name='hight_max_visitors',
            new_name='high_max_visitors',
        ),
    ]
