# Generated by Django 4.2.6 on 2023-12-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_rename_hight_max_visitors_notificationpreferencesmodel_high_max_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=32)),
                ('code', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
