# Generated by Django 4.2.6 on 2023-12-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_agentpermessionsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentpermessionsmodel',
            name='manage_agents',
        ),
        migrations.RemoveField(
            model_name='agentpermessionsmodel',
            name='manage_devices',
        ),
        migrations.AddField(
            model_name='agent',
            name='manage_agents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agent',
            name='manage_devices',
            field=models.BooleanField(default=False),
        ),
    ]
