# Generated by Django 4.2.6 on 2023-12-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_device_main'),
        ('client', '0019_remove_agentpermessionsmodel_manage_agents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpermessionsmodel',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.device'),
        ),
    ]
