# Generated by Django 4.2.6 on 2023-10-10 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='code',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='ip',
            field=models.IntegerField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='number_of_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
