# Generated by Django 4.2.6 on 2023-10-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_verificationcode_code_verificationcode_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
