# Generated by Django 4.2.6 on 2023-10-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_verificationcode_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='ip',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
