# Generated by Django 4.2.6 on 2023-10-20 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_verificationcode_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
