# Generated by Django 4.2.6 on 2023-11-01 12:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_user_id_alter_user_email'),
        ('administration', '0005_verificationcode_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='session_id',
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.CharField(max_length=8)),
                ('is_saled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.user')),
            ],
        ),
    ]
