# Generated by Django 4.2.6 on 2023-11-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_remove_verificationcode_session_id_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
    ]
