# Generated by Django 4.2.6 on 2023-11-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='token',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
