# Generated by Django 4.2.6 on 2023-12-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_verificationcode_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='max_visitors',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
