# Generated by Django 4.2.6 on 2023-12-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_device_max_visitors_device_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='main',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
